### ISSUE TITLE
Spike every 5 or 10 MHz depending on sample rate

### ISSUE THREAD

**Issue by jlxsolutions** [nepeee/limeSNA#1]
Not sure if my Limesdrmini has gone broken or the latest update from here but i can no longer measure antennas as every 5 or 10Mhz there is a spike depending on which samplerate i use
here's a screen shot spikes at 410 420 430 etc https://puu.sh/Ds8p6/ee52c6dda1.png done with a 50 Ohm calibration SMA plug

**Comment by nepeee** [comment]
The "spikes" caused by the bandwidth of the receiver, its normal. Use relative mode if you want to cancel it out. Its is possible to cancel it out by overlapping measurements(use only 60-70% of the available bandwidth) but its not implemented yet. You can reduce the bandwidth by editing the SingleToneSweeper.py at line 42:
self.bandWidth = round(sampleRate*0.7)

**Comment by jlxsolutions** [comment]
Odd did not have them before and measurements were correct now nothing matches.
How i tried today do sweeps with a short  press relative then do antenna still spikes every 5Mhz
then i did it with  the 50 ohm calibration sma still spikes every 5Mhz.
before i just ran sweep directly and antennas got measured pretty well
Guessing my Limemini is fudged up

**Comment by nepeee** [comment]
Take a look at the Y axes labels on your previous screenshot there is a max of 0.004(VSWR) error at the spikes, seems negligible.

To confirm any problem please take screenshots from the antenna measurements with/without calibration in dB and VSWR mode and also the 50ohm sma calibration resistor in absolute mode(dB).
